### ISSUE TITLE
JBoss thread-pool configuration changed in Camunda 7.6?

### ISSUE THREAD

**Issue by falko** [camunda/camunda-docs-manual#114]
The documentation talks about the creation of a thread pool for the Job Executor in the <subsystem xmlns="urn:jboss:domain:threads:1.1"> section:
```xml
<subsystem xmlns="urn:jboss:domain:threads:1.1">
  <bounded-queue-thread-pool name="job-executor-tp" allow-core-timeout="true">
    <core-threads count="3" />
    <queue-length count="3" />
    <max-threads count="10" />
    <keepalive-time time="10" unit="seconds" />
  </bounded-queue-thread-pool>
</subsystem>
```
but the current Wildfly distro doesn't have this section in it's configuration. There is only
```xml
           <job-executor>
                <core-threads>3</core-threads>
                <max-threads>5</max-threads>
                <queue-length>10</queue-length>
```

**Comment by hawky-4s-** [comment]
Hi @falko,
the Wildfly subsystem must be configured differently since Camunda 7.5 for Wildfly 8/10. This only applies to Wildfly, not JBoss AS 7.2
The update guide 7.4 -> 7.5 mentions it: https://docs.camunda.org/manual/7.6/update/minor/74-to-75/jboss/#configuration-of-job-executor-thread-pool-in-camunda-wildfly-8-subsystem

**Comment by falko** [comment]
Okay, my bad. I didn't see that there is another section on configuration on the same page:
https://docs.camunda.org/manual/7.6/installation/full/jboss/manual/#required-setup-for-wildfly-jboss-eap-7
