### ISSUE TITLE
External task query sql has a problem

### ISSUE THREAD

**Issue by sujun1992** [camunda/camunda-docs-manual#267]
When I create an external task query, I found that there were some problems with adding an variable filter.This sql parameter is wrong!
![image](https://user-images.githubusercontent.com/23478171/62447803-cafcfc00-b798-11e9-9982-f9ab72eaea83.png)

This parameter should be PROC_INST_ID_ !

**Comment by sujun1992** [comment]
![image](https://user-images.githubusercontent.com/23478171/62448771-1912ff00-b79b-11e9-9bd5-ab87e002a322.png)
This is the java code I used at the time.

**Comment by koevskinikola** [comment]
Hi @sujun1992,

Since you want to report a bug, please use our official issue tracker, we don't use GitHub as our issue tracker. You can find it here: https://app.camunda.com/jira/.

In general, it's better to provide the code examples in text form instead of images since it improves readability and it makes it easier to debug the problem on our side.

Since the problem you reported is not related to the Camunda docs, I'm closing this issue.

Best,
Nikola
